services:
  database:
    image: postgres
    container_name: postgres_service
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_DB=${PGDATABASE}
    healthcheck:
      test: "pg_isready --username=postgres"
      interval: 10s
      retries: 5
    ports:
      - "5432:5432"
  backend:
    build:
      context: Backend
      dockerfile: Dockerfile
    container_name: backend_service
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PGURI=${PGURI}
    ports:
      - "3000:3000"
  frontend:
    build:
      context: Frontend
      dockerfile: Dockerfile
    container_name: frontend_service
    depends_on:
      - backend
    ports:
      - "80:80"
